  - label: ":angular: Webview"
    env:
      NG_CLI_ANALYTICS: "false"
    commands:
      - export NG_CLI_ANALYTICS=false
      - .buildkite/build-webview-frontend
    plugins:
      - *merged-pr-plugin
      - compono/podman#main:
          <<: *podman-plugin-base
          volumes:
            - /var/lib/buildkite-agent/npm_cache:/root/.npm
