  - label: ":angular: Webview"
    command: .buildkite/build-webview-frontend
    plugins:
      - *merged-pr-plugin
      - kennasecurity/podman#master:
          <<: *podman-plugin-base
          volumes:
            - /var/lib/buildkite-agent/npm_cache:/home/builder/.npm
